[fileserver]
url = "https://account.vintagestory.at/files/stable/"
cdn_url = "https://cdn.vintagestory.at/gamefiles/stable/"

[local_server]
server_fullpath = "/absolute/path/to/your/server/"
backup_fullpath = "/absolute/path/to/your/server_backup/"
data_fullpath = "/absolute/path/to/your/data"
worldbackup_fullpath = "/absolute/path/to/your/data/WorldBackup"

[settings]
verbosity_level = 20

[discord.webhook]
success = ''
error = ''
